import Head from "next/head";

import { TodoListPage } from "@/templates/TodoListPage";
import { TaskProvider } from "@/taskContext";

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TaskProvider>
          <TodoListPage />
        </TaskProvider>
      </main>
    </>
  );
}
